#!/usr/bin/env node
/**
 * Keymaker Setup Script
 *
 * Adds the `keymaker` command to your PATH so you can run it from anywhere.
 */

import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const HOME = os.homedir();
const BIN_DIR = path.join(HOME, "bin");
const KEYMAKER_PATH = path.join(BIN_DIR, "keymaker");
const KEYMAKER_DIR = path.dirname(path.dirname(import.meta.url.replace("file://", "")));

// Detect shell config file
function getShellConfig(): string {
  const shell = process.env.SHELL || "/bin/zsh";
  if (shell.includes("zsh")) {
    return path.join(HOME, ".zshrc");
  } else if (shell.includes("bash")) {
    // Check for .bash_profile first (macOS), then .bashrc
    const bashProfile = path.join(HOME, ".bash_profile");
    if (fs.existsSync(bashProfile)) {
      return bashProfile;
    }
    return path.join(HOME, ".bashrc");
  }
  return path.join(HOME, ".profile");
}

function main() {
  console.log("╔════════════════════════════════════════════════════════════╗");
  console.log("║                   KEYMAKER SETUP                           ║");
  console.log("╚════════════════════════════════════════════════════════════╝");
  console.log();

  // Step 1: Create ~/bin directory if it doesn't exist
  console.log("1. Creating ~/bin directory...");
  if (!fs.existsSync(BIN_DIR)) {
    fs.mkdirSync(BIN_DIR, { recursive: true });
    console.log("   ✓ Created ~/bin");
  } else {
    console.log("   ✓ ~/bin already exists");
  }

  // Step 2: Create the keymaker wrapper script
  console.log("\n2. Creating keymaker command...");

  const wrapperScript = `#!/bin/bash
# Keymaker - Turnkey API Management Tool
# Auto-generated by keymaker setup

# Ensure pnpm is available
export PNPM_HOME="${path.join(HOME, "Library/pnpm")}"
export PATH="$PNPM_HOME:$PATH"

# Run keymaker
cd "${KEYMAKER_DIR}"
pnpm start "$@"
`;

  fs.writeFileSync(KEYMAKER_PATH, wrapperScript, { mode: 0o755 });
  console.log(`   ✓ Created ${KEYMAKER_PATH}`);

  // Step 3: Add ~/bin to PATH if needed
  console.log("\n3. Checking PATH...");
  const shellConfig = getShellConfig();
  const shellConfigContent = fs.existsSync(shellConfig)
    ? fs.readFileSync(shellConfig, "utf-8")
    : "";

  const pathExport = 'export PATH="$HOME/bin:$PATH"';

  if (
    shellConfigContent.includes("$HOME/bin") ||
    shellConfigContent.includes("~/bin") ||
    process.env.PATH?.includes(path.join(HOME, "bin"))
  ) {
    console.log("   ✓ ~/bin is already in PATH");
  } else {
    fs.appendFileSync(shellConfig, `\n# Added by keymaker setup\n${pathExport}\n`);
    console.log(`   ✓ Added ~/bin to PATH in ${shellConfig}`);
  }

  // Step 4: Check for .env.local
  console.log("\n4. Checking configuration...");
  const envLocalPath = path.join(KEYMAKER_DIR, ".env.local");
  const envExamplePath = path.join(KEYMAKER_DIR, ".env.local.example");

  if (fs.existsSync(envLocalPath)) {
    console.log("   ✓ .env.local exists");
  } else if (fs.existsSync(envExamplePath)) {
    console.log("   ⚠ .env.local not found");
    console.log("   → Copy .env.local.example to .env.local and add your credentials");
  }

  // Done!
  console.log("\n" + "═".repeat(60));
  console.log("\n✅ Setup complete!\n");
  console.log("To start using keymaker, either:");
  console.log(`  1. Open a new terminal, OR`);
  console.log(`  2. Run: source ${shellConfig}\n`);
  console.log("Then just type: keymaker");
  console.log("\n" + "═".repeat(60));
}

main();
